### ISSUE TITLE
Supported by tdewolff/canvas

### ISSUE THREAD

**Issue by tdewolff** [go-latex/latex#38]
Hey Sebastian, I've added support for this library by default with https://github.com/tdewolff/canvas/commit/5040a658ae12da048839230d182758287e311658. Users can opt-in to use the LaTeX binaries instead, by using the build tag `latex`. Really great work so far! Highly apreciated ;-)

I have a few questions regarding the library:
- What does `tex.Ship` do in https://github.com/go-latex/latex/blob/main/mtex/render.go#L37?
- What does `Depth()` mean in https://github.com/go-latex/latex/blob/main/mtex/render.go#L42?
- What does `Glyph.Offset` mean in https://github.com/go-latex/latex/blob/main/drawtex/canvas.go#L56?
- What is the difference between `Default`  and `Rm` fonts, and do I need to specify math versions of a font?
- Some functionality was missing I found, such as `left(` and `\right)`

Thanks for the work so far! I've also tried to use the STIX fonts you provide, but the glyph size or advance was bad in my case (maybe a problem at my end?). What is the status on supporting the Latin Modern fonts?

**Comment by sbinet** [comment]
hi,

> What does tex.Ship do in https://github.com/go-latex/latex/blob/main/mtex/render.go#L37?

`tex.Ship.Call` computes the bounding boxes of all glyphes in the parsed expression tree.

> What does Depth() mean in https://github.com/go-latex/latex/blob/main/mtex/render.go#L42?

depth is the "descent" of a glyph in TeX speak.

> What does Glyph.Offset mean in https://github.com/go-latex/latex/blob/main/drawtex/canvas.go#L56?

it's a compensating factor for handling math fonts:
https://github.com/go-latex/latex/blob/main/font/ttf/ttf.go#L146

> What is the difference between Default and Rm fonts, and do I need to specify math versions of a font?

here I've tried to follow what matplotlib did (which was itself trying to follow what TeX/LaTeX did to specify fonts).
theoretically, they should be the same in most cases, I think.
(ie: the default in TeX/LaTeX is to use roman fonts, except, of course when one is in "math mode")
go-latex hasn't support for an explicit extra set of "pure math" fonts (ie: having, say, `cmr10` + `cmex10`).

> Some functionality was missing I found, such as left( and \right)

yes. super/sub-scripts as well :)
that's why I started to attack the problem from another angle w/ the automatic translation of `tex.w` into Go:
- [star-tex.org/x/tex](https://star-tex.org/x/tex)
- [star-tex.org/x/tex/cmd/star-tex](https://star-tex.org/x/tex/cmd/star-tex)

that module hasn't yet a very convenient API being exposed to produce what `go-latex/mtex` does, but it's the goal.
as you know, it's missing handling of `pk` + `type1` fonts to be able to produce PNG/PDF documents from a DVI one.
once that's in, a complete TeX->DVI->{PNG,PDF} CI-test pipeline could be put in place and the work of breaking the whole `x/internal/xtex` package into smaller, focused and manageable ones could start.

**Comment by tdewolff** [comment]
Hey Sebastian, I hope all is well. Regarding your previous response, have there been any advances with the Star TeX project?

Anyways, I've pushed through an update to canvas, and it now includes a full rich text component as well as an improved version of using your LaTeX library (I wrote a custom backend for my purposes), e.g.: https://github.com/tdewolff/canvas/wiki/Fonts-&-Text

What is missing is parentheses, super/subscripts, etc. Do you think it would be easiest to add them to this repository? Or would you rather work on an API for the Star TeX repository instead?

**Comment by tdewolff** [comment]
Sorry, not sure where to make comments about Star TeX. Does it have a issue tracker or discussion forum? I was wondering if we could make it support `unicode-math` so that the proper OpenType `Latin Modern` fonts can be used.
